#!/usr/bin/env bash

INSTALL_DIR=$1
if [ -z "$INSTALL_DIR" ]; then
    echo "No install directory provided to set-path"
    exit 1
fi

INSTALL_DIR_ABS="$(cd "$INSTALL_DIR" && pwd)"
BUILDS_DIR="$INSTALL_DIR_ABS/builds"
mkdir -p "$BUILDS_DIR"
